spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #开启从注册中心动态创建路由的功能，利用微服务进行路由 lb://   生效
      routes:
        - id: guonei
          #sms_route #路由ID 没有固定规则要求,但是要求唯一  建议配合服务名
          #          uri: http://192.168.31.148:47777 #服务器的路由地址
          uri: https://news.baidu.com/guonei
          predicates:
            - Path=/guonei/**
            #断言，路径匹配进行路由

        - id: mil
          #sms_route #路由ID 没有固定规则要求,但是要求唯一  建议配合服务名
          #          uri: http://192.168.31.148:47777 #服务器的路由地址
          uri: https://news.baidu.com/mil
          predicates:
            - Path=/mil #断言，路径匹配进行路由

  redis:
    sysName: hhm_
    database: 1
    host:
    password:
    port:
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 5
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000

sys:
  #range 类型
  #app:需要校验X-Request-DeviceId
  #web:不需要任何校验  小程序，wap，公众号 都是h5类型的 web
  #all: app和web混用，
  # 配合 X-Request-deviceType [1-微信 2-WAP 3-Android 4-iOS 5-pc 6-手动创建 7-小程序] 3，4  需要传 X-Request-DeviceId
  range: app
  #001 开头会识别成1,已字符开头
  appId:
  appSecret: